name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y extra-cmake-modules qtbase5-dev libkf5coreaddons-dev \
          libkf5i18n-dev libkf5xmlgui-dev libkf5doctools-dev libkf5kio-dev

    - name: Configure
      run: cmake -DCMAKE_INSTALL_PREFIX=./install

    - name: Build
      run: make install

    - name: Package as .deb
      run: |
        mkdir -p package/DEBIAN
          # Create control file for Debian package
          echo "Package: mypackage" > package/DEBIAN/control
          echo "Version: 1.0" >> package/DEBIAN/control
          echo "Section: custom" >> package/DEBIAN/control
          echo "Priority: optional" >> package/DEBIAN/control
          echo "Architecture: all" >> package/DEBIAN/control
          echo "Essential: no" >> package/DEBIAN/control
          echo "Installed-Size: 1024" >> package/DEBIAN/control
          echo "Maintainer: YourName" >> package/DEBIAN/control
          echo "Description: My Package" >> package/DEBIAN/control
          cp -r ./install/* package/
          dpkg-deb --build package mypackage.deb

    - name: Debug
      run: |
        ls -la
        pwd
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: program-
        path: ./mypackage.deb
